title: Colaboradores
modelClass: Lacasita\Acciones\Models\Colaborador
list: $/lacasita/acciones/models/colaborador/columns.yaml
recordUrl: 'lacasita/acciones/colaboradores/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: order
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
