list: $/lacasita/acciones/models/accion/columns.yaml
modelClass: Lacasita\Acciones\Models\Accion
title: Acciones
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'lacasita/acciones/acciones/update/:id'
